### ISSUE TITLE
Problems with building the docker image

### ISSUE THREAD

**Issue by andluizsouza** [collinprather/streamlit-docker#1]
Nice job! This is an amazing and important topic for ML beginners. Many thanks!

I've tried to build the docker image, but I'm facing this error message:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n86_1yvn/pyarrow/setup.py", line 37, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n86_1yvn/pyarrow/
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1
```
Could you please point to me any suggestion/tip in order to solve that?

**Comment by collinprather** [comment]
Hi @andluizsouza! Glad to hear you've found the repo helpful.

This seems to be an issue with conflicting dependencies in the packages in `requirements.txt`. A good lesson for me moving forward, I should have included the _exact_ versions of the packages required! That said, this appears to be a [known issue with pyarrow](https://stackoverflow.com/questions/51608035/modulenotfounderror-no-module-named-cython-when-installing-pyarrow).

I'll have to do some debugging to find the solution!

**Comment by collinprather** [comment]
Hey @andluizsouza  - I just pushed a change that should solve your issue. I simply had to add the correct versions to the `requirements.txt` file.

Unfortunately, I have only tested this app with the following versions:

```
streamlit==0.51.0
numpy==1.18.1
pandas==1.0.0
scikit-learn==0.22.1
dtreeviz==0.6
```

Since I originally created this repo, I know that streamlit has matured considerably and added a lot of new features. I would recommend going through some of their new examples as well :)

I'm going to go ahead an close this issue, but feel free to re-open if you have any more problems!
